### ISSUE TITLE
"Add" from within forms on admins with subClasses wont work as expected

### ISSUE THREAD

**Issue by digitalkaoz** [sonata-project/SonataAdminBundle#2876]
if a relation points to an entity with a discriminator map, the "Add" Button doesnt work, because it tries to create the abstract parent class:

```php
/**
 * Class AbstractFilter
 *
 * @ORM\Entity()
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *  "value" = "Dl\Component\DomainModel\Filter\Condition\ValueFilter"
 * })
 * 
 */
abstract class AbstractFilter implements Filter
{
}

/**
 * Class ValueFilter
 *
 * @ORM\Entity()
 */
class ValueFilter extends AbstractFilter
{
}
````
i have admins for both and linked the childs into the parent:

```xml
        <service id="dl_filter.admin.abstract_filter" class="Dl\Bundle\FilterBundle\Admin\AbstractFilterAdmin">
            <tag name="sonata.admin" manager_type="orm" group="admin" label="AbstractFilter"/>
            <argument>null</argument>
            <argument>Dl\Component\DomainModel\Filter\Condition\AbstractFilter</argument>
            <argument>SonataAdminBundle:CRUD</argument>
            <call method="setSubClasses">
                <argument type="collection">
                    <argument key="value">Dl\Component\DomainModel\Filter\Condition\ValueFilter</argument>
                </argument>
            </call>
            <call method="addChild"><argument type="service" id="dl_filter.admin.value_filter" /></call>
        </service>

        <service id="dl_filter.admin.value_filter" class="Dl\Bundle\FilterBundle\Admin\ValueFilterAdmin">
            <tag name="sonata.admin" manager_type="orm" group="admin" label="ValueFilter"/>
            <argument>null</argument>
            <argument>Dl\Component\DomainModel\Filter\Condition\ValueFilter</argument>
            <argument>SonataAdminBundle:CRUD</argument>
        </service>
```

when using the from the "List View" the Menu Drop Down behaves correct, and gives me a "Add ValueFilter" Button to create a new Value Filter.

But when using it from within a form like this:

```php
//the admin
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('must', 'sonata_type_collection', ['label' => 'Must'], ['inline' => 'table', 'edit' => 'inline']) 
            //points to "dl_filter.admin.abstract_filter"
        ;
    }
```

i get an add button, but that wont work as the parent class is abstract...best would be the same dropdown like in the list view, or multiple buttons for each subClass.

Maybe im doing it wrong? Any Help?

**Comment by sfavot** [comment]
Same problem here. I was able to generate different add buttons for each subclasses by overriding the edit_orm_one_to_many template but of course it's not enough since the controller doesn't handle this case. The problem only occurs if you want to be able to add any type of children in your collection. If you only need to be able to add ValueFilter objects, you can fix the problem by specifying 'type_options' => ['data_class' => '\Dl\Component\DomainModel\Filter\Condition\ValueFilter'] when creating your form.

**Comment by rande** [comment]
Should be fixed by https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/501e0dcec17f8d847623b3c73310f258c052e5e2

**Comment by Tofandel** [comment]
Nope this doesn't fix it.

**Comment by OskarStark** [comment]
@Tofandel can you elaborate or do you have a fix which you could provide in a PR?

**Comment by Tofandel** [comment]
Well, there is still the same Add button in inline (so no dropdown) and so it's still throwing the same error: Cannot initialize abstract class.
I tried a lot of things and I can't find a way to get the dropdown, so the only thing that does work is displaying it in a modal.

I also have an issue with my sonata_entity_collection, once it has childrens, it's not displayed correctly on the page : 
![image](https://user-images.githubusercontent.com/6115458/27582939-0904a2ce-5b33-11e7-9ce6-a280cde790af.png)

I would expect a button to open a modal to edit the Children, but instead I just get all of the fields within the parent form and it's all a big mess. Not really related, but do you happen to know where could I be doing something wrong ? Maybe some twig form_theme config I'm missing, but I can't find it documented, thanks.
